# Generated by Django 3.1.3 on 2021-01-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.FileField(default='img.jpg', upload_to=''),
        ),
    ]
