# Generated by Django 3.1.3 on 2021-01-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0002_auto_20210104_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
