# Generated by Django 3.1.3 on 2021-01-09 08:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findwork', '0005_auto_20210109_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='get to know us', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=cloudinary.models.CloudinaryField(default='image.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee')], max_length=10),
        ),
    ]
